### ISSUE TITLE
Modal window styling

### ISSUE THREAD

**Issue by christopherthomasdesign** [markhurrell/govuk-design-patterns#1]
Started putting the modal window on top of some pages from services, with the shade layer in between. These are quick Sketch mockups so things like the shade styling are a rough approximation of the CSS...

<img width="1059" alt="screen shot 2018-09-13 at 13 45 29" src="https://user-images.githubusercontent.com/19834460/45489257-ba482f80-b75b-11e8-8314-9d50b8a6d547.png">

Wonder if there will be occasions when the colour is going to clash? Especially on top of blue 'interruptor' sort of screens like you get in passports, Verify etc. Hard to strike the balance between the modal layer having enough contrast and the layer below being visible enough to keep context.

I also think there's something about the way it looks like GOV.UK on top of GOV.UK that might make it look like an ad or spam despite the consistent branding. 

Here's the thing @conordelahunty did which looks shaaarp:

<img width="1135" alt="screen shot 2018-09-13 at 14 02 25" src="https://user-images.githubusercontent.com/19834460/45490332-b7027300-b75e-11e8-92d3-7e8f6a5c9df0.png">

I think removing the separation of the top black bar makes it look much less like a website on top of another website.

I tried a compromise-ish version which takes our existing button styling and puts it on an all black window. This would make it very unlikely to clash with the layer below. 

We pretty much never do things in all black... maybe it looks a bit heavy. But it is heavy cos your application's about to time out so...

<img width="1137" alt="screen shot 2018-09-13 at 13 46 21" src="https://user-images.githubusercontent.com/19834460/45489519-58d49080-b75c-11e8-8069-5bbd938cd2d7.png">

Thoughts?

**Comment by markhurrell** [comment]
makes sense to me, have updated the design 
https://github.com/markhurrell/govuk-design-patterns/commit/fc99fc3aa8e52dc9ea123787700f3e088d95a995

**Comment by soniaturcotte** [comment]
I really like the all black version, but we'd have to be pretty rigid on how much content is allowed inside. Anthing more than a short sentence or two will be _intense_
